name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Install dependencies
        run: dotnet restore src/Datalite.sln
      - name: Build
        run: dotnet build src/Datalite.sln --configuration Release --no-restore
      - name: Establish Test Filter
        run: dotnet run --project src/TestDeterminer/TestDeterminer.csproj
      - name: Set FILTER environment variable
        run: |
          F=$(cat filter.txt)
          echo "FILTER=$F" >> $GITHUB_ENV
      - name: Test
        run: dotnet test src/Datalite.sln --no-restore --no-build --configuration Release --filter "${{ env.FILTER }}" --logger "trx;LogFileName=test-results.trx" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: "**/test-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true